### ISSUE TITLE
Where did you get these values?

### ISSUE THREAD

**Issue by xaviablaza** [CrystalFerrai/MakeFwl#1]
Hi @CrystalFerrai ! I'm wondering where you got these values from? I'm assuming that the WorldVersion and the GenVersion has changed since the release of the game, and I'm wondering if this would affect the format of the `.fwl` files generated.

https://github.com/CrystalFerrai/MakeFwl/blob/af5835fed328900fc037094769a5553349e21b38/MakeFwl/Program.cs#L23

https://github.com/CrystalFerrai/MakeFwl/blob/af5835fed328900fc037094769a5553349e21b38/MakeFwl/Program.cs#L24

**Comment by CrystalFerrai** [comment]
The versions are from the Version class in assembly_valheim. i added some comments to the code explaining them a bit.  The current WorldVersion in the game is 27 and the tool writes 26. There does not appear to be any difference between those versions though. The game will load versions as old as version 9. The GenVersion was introduced as 1 with WorldVersion 26 and has not changed yet.

**Comment by xaviablaza** [comment]
Thank you! Appreciate your response :)
